version: "3"

services:
  server:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/build/server/Dockerfile
    command: ./server
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: "8080"
      SERVER_CONN_POOL_SIZE: "100"
      SERVER_CONN_TTL: "1s"
