version: "3"

services:
  server:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/build/server/Dockerfile
    command: ./server
    environment:
      SERVER_PORT: "1234"
      SERVER_CONN_POOL_SIZE: "100"
      SERVER_CONN_TTL: "1s"

  client:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/build/client/Dockerfile
    command: ./client
    environment:
      CLIENT_ADDRESS: "server:1234"
      CLIENT_DELAY: "1s"
      CLIENT_CONN_TTL: "100ms"
    depends_on:
      - server
